"""RC4 signal decryption for PineTunnel.

Supports RC4-drop256 stream cipher encryption of webhook payloads.
PineScript encrypts the entire signal (license key + command + params)
before sending to TradingView. The server decrypts before parsing.

Format: RC4,<nonce_hex>:<ct_hex>:<checksum_hex>

- nonce: 8 bytes (from bar time + bar index in PineScript)
- ct: RC4-encrypted plaintext (key + nonce as key material, drop-256)
- checksum: 4-byte XOR-fold integrity check over ciphertext

Key: SIGNAL_ENCRYPTION_KEY env var (64-char hex = 32 bytes).
Generated by `pinetunnel setup` and sent to admin via Telegram bot.

Auto-detection: if message starts with "RC4,", server decrypts.
Otherwise, treated as plaintext (backward compatible).
"""

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

# RC4-drop256: discard first 256 keystream bytes to mitigate FMS attacks.
# MUST match the constant in PineTunnel.pine's _rc4Encrypt function.
_RC4_DROP_BYTES = 256

# Key from environment (64-char hex = 32 bytes)
_KEY_HEX: Optional[str] = None
_KEY_BYTES_CACHE: Optional[bytes] = None

# Previous key for staged rotation
_PREV_KEY_HEX: Optional[str] = None
_PREV_KEY_BYTES_CACHE: Optional[bytes] = None


def _load_key() -> Optional[bytes]:
    """Load and cache the encryption key from SIGNAL_ENCRYPTION_KEY env var."""
    global _KEY_HEX, _KEY_BYTES_CACHE
    key_hex = os.environ.get("SIGNAL_ENCRYPTION_KEY", "")
    if key_hex == _KEY_HEX and _KEY_BYTES_CACHE is not None:
        return _KEY_BYTES_CACHE
    _KEY_HEX = key_hex
    if not key_hex or len(key_hex) != 64:
        _KEY_BYTES_CACHE = None
        return None
    try:
        _KEY_BYTES_CACHE = bytes.fromhex(key_hex)
        return _KEY_BYTES_CACHE
    except ValueError:
        logger.error("SIGNAL_ENCRYPTION_KEY is not valid hex")
        _KEY_BYTES_CACHE = None
        return None


def _load_prev_key() -> Optional[bytes]:
    """Load previous key for staged rotation."""
    global _PREV_KEY_HEX, _PREV_KEY_BYTES_CACHE
    key_hex = os.environ.get("SIGNAL_ENCRYPTION_KEY_PREVIOUS", "")
    if key_hex == _PREV_KEY_HEX and _PREV_KEY_BYTES_CACHE is not None:
        return _PREV_KEY_BYTES_CACHE
    _PREV_KEY_HEX = key_hex
    if not key_hex or len(key_hex) != 64:
        _PREV_KEY_BYTES_CACHE = None
        return None
    try:
        _PREV_KEY_BYTES_CACHE = bytes.fromhex(key_hex)
        return _PREV_KEY_BYTES_CACHE
    except ValueError:
        logger.error("SIGNAL_ENCRYPTION_KEY_PREVIOUS is not valid hex")
        _PREV_KEY_BYTES_CACHE = None
        return None


def _rc4_ksa(key: bytes) -> list[int]:
    """RC4 Key Scheduling Algorithm."""
    s = list(range(256))
    j = 0
    key_len = len(key)
    for i in range(256):
        j = (j + s[i] + key[i % key_len]) % 256
        s[i], s[j] = s[j], s[i]
    return s


def _rc4_prga(s: list[int], n: int) -> bytes:
    """RC4 Pseudo-Random Generation Algorithm."""
    i = 0
    j = 0
    result = bytearray(n)
    for idx in range(n):
        i = (i + 1) % 256
        j = (j + s[i]) % 256
        s[i], s[j] = s[j], s[i]
        result[idx] = s[(s[i] + s[j]) % 256]
    return bytes(result)


def _xor_fold(data: bytes, n: int) -> bytes:
    """XOR-fold data into n bytes (integrity checksum matching PineScript)."""
    result = bytearray(n)
    for i, b in enumerate(data):
        result[i % n] ^= b
    return bytes(result)


def _try_rc4(key: bytes, nonce: bytes, ct: bytes) -> Optional[str]:
    """Attempt RC4-drop256 decrypt + ASCII decode with a specific key.

    Returns plaintext on success, None silently on failure (wrong key ->
    non-ASCII bytes -> decode error -> None).
    """
    combined_key = key + nonce
    s = _rc4_ksa(combined_key)
    _rc4_prga(s, _RC4_DROP_BYTES)
    keystream = _rc4_prga(s, len(ct))
    plaintext_bytes = bytes(a ^ b for a, b in zip(ct, keystream))
    try:
        return plaintext_bytes.decode("ascii")
    except (UnicodeDecodeError, ValueError):
        return None


def is_encrypted_message(message: str) -> bool:
    """Check if a message is RC4-encrypted.

    Format: RC4,<payload> (license key is inside the encrypted payload).
    """
    if not message:
        return False
    parts = message.split(",", 1)
    return len(parts) == 2 and parts[0].strip().upper() == "RC4"


def is_encryption_configured() -> bool:
    """Check if the encryption key is properly configured."""
    return _load_key() is not None


def parse_rc4_payload(payload: str) -> Optional[tuple[str, str, str]]:
    """Parse RC4 payload format: <nonce_hex>:<ct_hex>:<checksum_hex>.

    Returns (nonce_hex, ct_hex, checksum_hex) or None if invalid.
    """
    parts = payload.split(":")
    if len(parts) != 3:
        return None
    nonce_hex, ct_hex, checksum_hex = parts
    if len(nonce_hex) != 16:  # 8 bytes = 16 hex chars
        return None
    if len(ct_hex) < 2:  # At least 1 byte
        return None
    if len(checksum_hex) != 8:  # 4 bytes = 8 hex chars
        return None
    return nonce_hex, ct_hex, checksum_hex


def decrypt_rc4_signal(nonce_hex: str, ct_hex: str, checksum_hex: str) -> Optional[str]:
    """Decrypt an RC4-encrypted PineTunnel signal with checksum verification.

    Verifies checksum (key-independent, detects tampering) before decryption.
    Tries current key first, then previous key for staged rotation.

    Args:
        nonce_hex: Hex-encoded 8-byte nonce.
        ct_hex: Hex-encoded ciphertext.
        checksum_hex: Hex-encoded 4-byte checksum.

    Returns:
        Decrypted plaintext string, or None on failure.
    """
    key = _load_key()
    if key is None:
        logger.error("RC4 decryption requested but no key configured")
        return None

    try:
        nonce = bytes.fromhex(nonce_hex)
        ct = bytes.fromhex(ct_hex)
        checksum = bytes.fromhex(checksum_hex)
    except ValueError:
        logger.error("Invalid hex in RC4 encrypted signal")
        return None

    if len(nonce) != 8:
        logger.error("Invalid RC4 nonce length: %d", len(nonce))
        return None

    if len(ct) == 0:
        logger.error("Empty RC4 ciphertext")
        return None

    if len(checksum) != 4:
        logger.error("Invalid RC4 checksum length: %d", len(checksum))
        return None

    # Verify checksum BEFORE decryption (detects tampering without key)
    expected_checksum = _xor_fold(ct, 4)
    if checksum != expected_checksum:
        logger.warning("RC4 checksum mismatch - signal rejected (possible tampering)")
        return None

    # Try current key
    plaintext = _try_rc4(key, nonce, ct)
    if plaintext is not None:
        return plaintext

    # Fallback to previous key (staged rotation)
    prev_key = _load_prev_key()
    if prev_key is not None and prev_key != key:
        plaintext = _try_rc4(prev_key, nonce, ct)
        if plaintext is not None:
            return plaintext

    logger.warning("RC4 decryption failed - signal rejected")
    return None


def generate_encryption_key() -> str:
    """Generate a new 64-char hex encryption key (32 bytes).

    Use secrets.token_hex(32) for cryptographic randomness.
    """
    import secrets
    return secrets.token_hex(32)
