"""Nginx reverse proxy and Let's Encrypt SSL setup for PineTunnel.

Provides:
- detect_domain: Extract domain from server URL (returns None for IP addresses)
- check_nginx_installed: Check and offer to install nginx
- generate_nginx_config: Generate nginx server block config
- install_nginx_config: Write, symlink, test, and reload nginx config
- setup_ssl: Obtain Let's Encrypt SSL certificate via certbot
- setup_reverse_proxy: Main orchestrator for full proxy + SSL setup
"""

from __future__ import annotations

import ipaddress
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import urlparse

from apps.cli.main import (
    _is_windows_admin,
    _sudo_prefix,
    print_fail,
    print_ok,
    print_skip,
    print_warn,
)


def detect_domain(server_url: str) -> str | None:
    """Parse server URL and return domain name, or None if it's an IP address."""
    try:
        parsed = urlparse(server_url)
        hostname = parsed.hostname
    except Exception:
        return None

    if not hostname:
        return None

    try:
        ipaddress.ip_address(hostname)
        return None
    except ValueError:
        return hostname


def check_nginx_installed() -> bool:
    """Check if nginx is installed, offer to install if not."""
    if shutil.which("nginx"):
        print_ok("nginx is installed")
        return True

    print_warn("nginx is not installed")
    system = platform.system()

    if system == "Darwin":
        install_cmd = ["brew", "install", "nginx"]
    elif system == "Linux":
        if shutil.which("apt") or shutil.which("apt-get"):
            install_cmd = _sudo_prefix() + ["apt", "install", "-y", "nginx"]
        elif shutil.which("dnf"):
            install_cmd = _sudo_prefix() + ["dnf", "install", "-y", "nginx"]
        elif shutil.which("yum"):
            install_cmd = _sudo_prefix() + ["yum", "install", "-y", "nginx"]
        else:
            print_fail("Could not detect package manager. Install nginx manually.")
            return False
    elif system == "Windows":
        # Check common Windows nginx install paths
        for p in ["C:/nginx/nginx.exe", "C:/Program Files/nginx/nginx.exe"]:
            if Path(p).exists():
                print_ok(f"nginx found at {p}")
                return True
        print("  Install nginx:")
        print("    winget install nginx.nginx")
        print("    choco install nginx")
        print("    Or download from https://nginx.org/en/download.html")
        return False
    else:
        print_fail(f"Unsupported OS: {system}")
        return False

    try:
        answer = input("  Install nginx now? [Y/n]: ").strip().lower()
    except (KeyboardInterrupt, EOFError):
        answer = "n"

    if answer == "n":
        print_skip("nginx installation (user declined)")
        return False

    print(f"  Running: {' '.join(install_cmd)}")
    try:
        result = subprocess.run(install_cmd, timeout=120)
        if result.returncode != 0:
            print_fail("nginx installation failed")
            return False
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as e:
        print_fail(f"nginx installation failed: {e}")
        return False

    if shutil.which("nginx"):
        print_ok("nginx installed successfully")
        return True

    print_fail("nginx installed but binary not found in PATH")
    return False


def generate_nginx_config(domain: str, port: int, ssl: bool = False) -> str:
    """Generate a complete nginx server block config for reverse proxy."""
    if ssl:
        return f"""# PineTunnel reverse proxy - {domain} (SSL)
# Generated by pinetunnel setup-proxy

server {{
    listen 80;
    server_name {domain};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    server_name {domain};

    ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    client_max_body_size 1m;

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }}
}}
"""
    else:
        return f"""# PineTunnel reverse proxy - {domain} (HTTP)
# Generated by pinetunnel setup-proxy

server {{
    listen 80;
    server_name {domain};

    client_max_body_size 1m;

    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options DENY;

    location / {{
        proxy_pass http://127.0.0.1:{port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }}
}}
"""


def install_nginx_config(config: str, domain: str) -> bool:
    """Write nginx config, create symlink, test, and reload."""
    system = platform.system()

    if system == "Linux":
        config_path = "/etc/nginx/sites-available/pinetunnel"
        enabled_path = "/etc/nginx/sites-enabled/pinetunnel"

        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".conf", delete=False
        ) as f:
            f.write(config)
            temp_path = f.name

        try:
            result = subprocess.run(
                _sudo_prefix() + ["cp", temp_path, config_path],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                print_fail(f"Could not write config: {result.stderr.strip()}")
                return False
            print_ok(f"Config written to {config_path}")

            result = subprocess.run(
                _sudo_prefix() + ["ln", "-sf", config_path, enabled_path],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                print_warn(f"Could not create symlink: {result.stderr.strip()}")
                print(f"         Try: sudo ln -s {config_path} {enabled_path}")
            else:
                print_ok(f"Symlink enabled: {enabled_path}")
        finally:
            try:
                os.unlink(temp_path)
            except OSError:
                pass

        result = subprocess.run(
            _sudo_prefix() + ["nginx", "-t"], capture_output=True, text=True
        )
        if result.returncode != 0:
            print_fail("nginx config test failed")
            err = result.stderr.strip() or result.stdout.strip()
            if err:
                print(f"         {err}")
            return False
        print_ok("nginx config test passed")

        result = subprocess.run(
            _sudo_prefix() + ["systemctl", "reload", "nginx"],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print_warn(f"Could not reload nginx: {result.stderr.strip()}")
            print("         Try: sudo systemctl reload nginx")
            return False
        print_ok("nginx reloaded")
        return True

    elif system == "Darwin":
        if Path("/opt/homebrew").exists():
            brew_prefix = "/opt/homebrew"
        elif Path("/usr/local").exists():
            brew_prefix = "/usr/local"
        else:
            print_fail("Homebrew not found. Install nginx with: brew install nginx")
            return False

        servers_dir = Path(f"{brew_prefix}/etc/nginx/servers")
        config_file = servers_dir / "pinetunnel.conf"

        try:
            servers_dir.mkdir(parents=True, exist_ok=True)
            config_file.write_text(config)
            print_ok(f"Config written to {config_file}")
        except (PermissionError, OSError) as e:
            print_fail(f"Could not write config: {e}")
            return False

        result = subprocess.run(
            ["nginx", "-t"], capture_output=True, text=True
        )
        if result.returncode != 0:
            print_fail("nginx config test failed")
            err = result.stderr.strip() or result.stdout.strip()
            if err:
                print(f"         {err}")
            return False
        print_ok("nginx config test passed")

        result = subprocess.run(
            ["nginx", "-s", "reload"], capture_output=True, text=True
        )
        if result.returncode != 0:
            print_warn(f"Could not reload nginx: {result.stderr.strip()}")
            print("         Try: brew services restart nginx")
            return False
        print_ok("nginx reloaded")
        return True

    elif system == "Windows":
        # Find nginx installation directory
        nginx_exe = shutil.which("nginx")
        if nginx_exe:
            nginx_dir = Path(nginx_exe).parent
        else:
            # Check common Windows nginx paths
            for p in ["C:/nginx", "C:/Program Files/nginx"]:
                if (Path(p) / "nginx.exe").exists():
                    nginx_dir = Path(p)
                    break
            else:
                print_fail("nginx not found. Install nginx or add it to PATH.")
                print("         Install: winget install nginx.nginx")
                return False

        conf_d = nginx_dir / "conf" / "conf.d"
        try:
            conf_d.mkdir(parents=True, exist_ok=True)
        except OSError:
            pass

        config_file = conf_d / "pinetunnel.conf"

        try:
            config_file.write_text(config)
            print_ok(f"Config written to {config_file}")
        except (PermissionError, OSError) as e:
            print_fail(f"Could not write config: {e}")
            print("         Try running as Administrator")
            return False

        # Ensure conf.d is included in nginx.conf
        nginx_conf = nginx_dir / "conf" / "nginx.conf"
        if nginx_conf.exists():
            try:
                conf_text = nginx_conf.read_text()
                if "conf.d" not in conf_text:
                    print_warn(f"Add this to {nginx_conf} inside the http block:")
                    print("         include conf.d/*.conf;")
            except OSError:
                pass

        # Test config
        nginx_bin = str(nginx_dir / "nginx.exe") if not nginx_exe else "nginx"
        result = subprocess.run(
            [nginx_bin, "-t"], capture_output=True, text=True
        )
        if result.returncode != 0:
            print_fail("nginx config test failed")
            err = result.stderr.strip() or result.stdout.strip()
            if err:
                print(f"         {err}")
            return False
        print_ok("nginx config test passed")

        # Reload
        result = subprocess.run(
            [nginx_bin, "-s", "reload"], capture_output=True, text=True
        )
        if result.returncode != 0:
            print_warn(f"Could not reload nginx: {result.stderr.strip()}")
            print("         Try: nginx -s reload (as Administrator)")
            return False
        print_ok("nginx reloaded")
        return True

    else:
        print_fail(f"Unsupported OS: {system}")
        return False


def setup_ssl(domain: str) -> bool:
    """Obtain Let's Encrypt SSL certificate via certbot."""
    system = platform.system()

    if not shutil.which("certbot"):
        print_warn("certbot is not installed")

        if system == "Linux":
            if shutil.which("apt") or shutil.which("apt-get"):
                install_cmd = _sudo_prefix() + [
                    "apt", "install", "-y",
                    "certbot", "python3-certbot-nginx",
                ]
            elif shutil.which("dnf"):
                install_cmd = _sudo_prefix() + [
                    "dnf", "install", "-y",
                    "certbot", "python3-certbot-nginx",
                ]
            else:
                print_fail("Could not detect package manager. Install certbot manually.")
                print("         See: https://certbot.eff.org/")
                return False

            try:
                answer = input("  Install certbot now? [Y/n]: ").strip().lower()
            except (KeyboardInterrupt, EOFError):
                answer = "n"

            if answer == "n":
                print_skip("SSL setup (certbot not installed)")
                return False

        elif system == "Windows":
            # On Windows, certbot can be installed via pip
            print("  SSL options for Windows:")
            print("    1. certbot via pip:")
            print(f"       pip install certbot && certbot --nginx -d {domain}")
            print("    2. win-acme (recommended for Windows):")
            print("       Download from https://www.win-acme.com/")
            print("    3. Caddy (auto-HTTPS, no certbot needed):")
            print("       winget install caddy.caddy")
            print("       Caddy handles SSL automatically")
            print()
            try:
                answer = input(
                    "  Install certbot via pip? [Y/n]: "
                ).strip().lower()
            except (KeyboardInterrupt, EOFError):
                answer = "n"

            if answer == "n":
                print_skip("SSL setup (certbot not installed)")
                return False

            install_cmd = [sys.executable, "-m", "pip", "install", "certbot"]
        else:
            print_fail(f"certbot auto-install not supported on {system}")
            print("         See: https://certbot.eff.org/")
            return False

        print(f"  Running: {' '.join(install_cmd)}")
        try:
            result = subprocess.run(install_cmd, timeout=120)
            if result.returncode != 0:
                print_fail("certbot installation failed")
                return False
            print_ok("certbot installed")
        except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as e:
            print_fail(f"certbot installation failed: {e}")
            return False

    print(f"  Running certbot for {domain}...")

    cmd = _sudo_prefix() + [
        "certbot", "--nginx",
        "-d", domain,
        "--non-interactive",
        "--agree-tos",
        "--redirect",
    ]

    email = os.environ.get("SECURITY_EMAIL", "")
    if email and "@" in email and "your-server.com" not in email:
        cmd.extend(["-m", email])
    else:
        cmd.append("--register-unsafely-without-email")

    try:
        result = subprocess.run(cmd, timeout=120)
        if result.returncode != 0:
            print_fail("certbot failed to obtain certificate")
            return False
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as e:
        print_fail(f"certbot failed: {e}")
        return False

    if system == "Windows":
        cert_dir = Path("C:/Certbot/live") / domain
    else:
        cert_dir = Path(f"/etc/letsencrypt/live/{domain}")
    if cert_dir.exists():
        print_ok(f"SSL certificate obtained for {domain}")
        return True

    print_fail(f"Certificate not found at {cert_dir}")
    return False


def setup_reverse_proxy(domain: str | None, port: int) -> bool:
    """Main orchestrator: set up nginx reverse proxy and optional SSL."""
    if not domain:
        print()
        print("  PineTunnel Reverse Proxy Setup")
        print()
        print_warn("No domain name detected (IP address only).")
        print()
        print("  TradingView webhooks work with HTTP, but HTTPS requires a domain.")
        print()
        print("  To use HTTPS:")
        print("    1. Point a domain name to this server's IP address")
        print("    2. Set SERVER_BASE_URL in .env to http://your-domain.com")
        print("    3. Run: pinetunnel setup-proxy")
        print()
        print("  Without HTTPS, use the HTTP webhook URL directly.")
        return False

    print()
    print("  PineTunnel Reverse Proxy Setup")
    print(f"  Domain: {domain}")
    print(f"  Backend: 127.0.0.1:{port}")
    print()

    if not check_nginx_installed():
        print_fail("nginx is required for reverse proxy setup.")
        return False

    print()
    print("  Step 1: Installing nginx config (HTTP)...")
    http_config = generate_nginx_config(domain, port, ssl=False)
    if not install_nginx_config(http_config, domain):
        print_fail("Failed to install nginx config.")
        return False

    print()
    print("  Step 2: SSL setup via Let's Encrypt...")
    try:
        answer = input("  Set up HTTPS with Let's Encrypt? [Y/n]: ").strip().lower()
    except (KeyboardInterrupt, EOFError):
        answer = "n"

    if answer == "n":
        print_skip("SSL setup (user declined)")
        print()
        print_ok(f"Reverse proxy is running on http://{domain}")
        print(f"  Webhook URL: http://{domain}/")
        return True

    if not setup_ssl(domain):
        print_warn("SSL setup failed. HTTP proxy is still active.")
        print_ok(f"Reverse proxy is running on http://{domain}")
        print(f"  Webhook URL: http://{domain}/")
        return True

    print()
    print("  Step 3: Updating nginx config with SSL...")
    ssl_config = generate_nginx_config(domain, port, ssl=True)
    if not install_nginx_config(ssl_config, domain):
        print_warn("Failed to install SSL config. HTTP proxy is still active.")
        return True

    print()
    print_ok(f"Reverse proxy is running on https://{domain}")
    print(f"  Webhook URL: https://{domain}/")
    print()
    print("  SSL certificate auto-renews via certbot timer.")
    return True
